### ISSUE TITLE
Invalid git link path! Please check A git repository in ...\A\_externals\B\_externals\A

### ISSUE THREAD

**Issue by andry81** [chronoxor/gil#7]
I have trying to port my projects from svn into git and using your project as a replacement for `svn:externals`.

Main issue here is that the svn externals does support recurrent externals (circular dependency without recursion):

```
A -> B/subdirX
B -> A/subdirY
```

, where subdirX and subdirY has no externals.

```
Traceback (most recent call last):
  File "C:\Python\x64\310\Scripts\gil.py", line 419, in <module>
    sys.exit(main())
  File "C:\Python\x64\310\Scripts\gil.py", line 406, in main
    context.link()
  File "C:\Python\x64\310\Scripts\gil.py", line 180, in link
    self.link_recursive(root)
  File "C:\Python\x64\310\Scripts\gil.py", line 190, in link_recursive
    self.link_path(d)
  File "C:\Python\x64\310\Scripts\gil.py", line 203, in link_path
    return self.update_links(path, filename)
  File "C:\Python\x64\310\Scripts\gil.py", line 246, in update_links
    raise Exception("%s:%d: Invalid git link path! Please check %s git repository in %s" % (filename, index, gil_name, gil_path))
Exception: ...\contools\_externals\svncmd\.gitlinks:0: Invalid git link path! Please check contools git repository in ...\contools\_externals\svncmd\_externals\contools
```
Here the `A` is `contools`, `B` is `svncmd`.

Seems when you do create recurring dependency at some point `gil update` can crash with the exception.

As a workaround erasing the `A\_externals` and rerun `gil update` fixes the problem.

**Comment by chronoxor** [comment]
https://github.com/chronoxor/gil?tab=readme-ov-file#sample-with-recursion
