### ISSUE TITLE
fatal: detected dubious ownership in repository at '...\A\_externals\X'

### ISSUE THREAD

**Issue by andry81** [chronoxor/gil#8]
Details is here: https://github.com/chronoxor/gil/issues/7

```
...\contools>gil pull
Working path: ...\contools
Discover git links: ...\contools\.gitlinks
Discover git links: ...\contools\_externals\svncmd\.gitlinks
Discover git links: ...\contools\_externals\tacklelib\.gitlinks
Running: git pull in ...\contools
Already up to date.
Running: git checkout branch "20101227" in ...\contools\_externals\gnuwin32
fatal: detected dubious ownership in repository at '.../contools/_externals/gnuwin32'
'.../contools/_externals/gnuwin32' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-777288001-2747175061-911012717-1000'
To add an exception for this directory, call:

        git config --global --add safe.directory '.../contools/_externals/gnuwin32'
Traceback (most recent call last):
  File "C:\Python\x64\310\Scripts\gil.py", line 419, in <module>
    sys.exit(main())
  File "C:\Python\x64\310\Scripts\gil.py", line 411, in main
    context.command(sys.argv[1], sys.argv[2:])
  File "C:\Python\x64\310\Scripts\gil.py", line 261, in command
    self.git_checkout(record.path, record.branch)
  File "C:\Python\x64\310\Scripts\gil.py", line 328, in git_checkout
    raise Exception("Failed to run git checkout branch \"%s\" in %s" % (branch, path))
Exception: Failed to run git checkout branch "20101227" in ...\contools\_externals\gnuwin32
```

I think this is somehow connected to `gil update` has been ran once under Administrator console to allocate symbolic links in other externals.
So to avoid that needs to call the git executable under unelevated privileges to avoid create directories under elevated one.

**Comment by chronoxor** [comment]
https://github.com/chronoxor/gil?tab=readme-ov-file#sample-with-recursion

**Comment by chronoxor** [comment]
https://github.com/chronoxor/gil?tab=readme-ov-file#sample-with-recursion
