### ISSUE TITLE
error: cannot spawn git: Filename too long

### ISSUE THREAD

**Issue by andry81** [chronoxor/gil#9]
Details is here: https://github.com/chronoxor/gil/issues/7

The issue is that the `git status`, `git commit` and all other commands falls into recursion reading recursed submodules:

```
...\tacklelib>gil pull
Working path: ...\tacklelib
Discover git links: ...\tacklelib\.gitlinks
Discover git links: ...\tacklelib\_externals\contools\.gitlinks
Discover git links: ...\tacklelib\_externals\contools\_externals\svncmd\.gitlinks
Discover git links: ...\tacklelib\_externals\contools\_externals\tacklelib\.gitlinks
Running: git pull in ...\tacklelib
Already up to date.
Running: git checkout branch "master" in ...\tacklelib\_externals\contools
error: cannot spawn git: Filename too long
fatal: Could not run 'git status --porcelain=2' in submodule _externals/contools
fatal: 'git status --porcelain=2' failed in submodule _externals/svncmd
fatal: 'git status --porcelain=2' failed in submodule _externals/contools
fatal: 'git status --porcelain=2' failed in submodule _externals/svncmd
fatal: 'git status --porcelain=2' failed in submodule _externals/contools
 ...
fatal: 'git status --porcelain=2' failed in submodule _externals/contools
fatal: 'git status --porcelain=2' failed in submodule _externals/svncmd
fatal: 'git status --porcelain=2' failed in submodule _externals/contools
fatal: 'git status --porcelain=2' failed in submodule _externals/svncmd
Traceback (most recent call last):
  File "C:\Python\x64\310\Scripts\gil.py", line 419, in <module>
    sys.exit(main())
  File "C:\Python\x64\310\Scripts\gil.py", line 411, in main
    context.command(sys.argv[1], sys.argv[2:])
  File "C:\Python\x64\310\Scripts\gil.py", line 261, in command
    self.git_checkout(record.path, record.branch)
  File "C:\Python\x64\310\Scripts\gil.py", line 328, in git_checkout
    raise Exception("Failed to run git checkout branch \"%s\" in %s" % (branch, path))
Exception: Failed to run git checkout branch "master" in ...\tacklelib\_externals\contools
```

So the recursion problem is not actually resolved as stated in the readme. Or this is not the recursion and something else.

**Comment by chronoxor** [comment]
https://github.com/chronoxor/gil?tab=readme-ov-file#sample-with-recursion
